#!/usr/bin/env bash
set -euo pipefail
# Build a markdown release body for a testnet deployment.
#
# Env inputs:
#   BROADCAST_FILE  — required, path to run-latest.json
#   BLOCKSCOUT_URL  — required
#   NETWORK_NAME    — required
#   CHAIN_ID        — required
#   PR_NUMBER       — required
#   PR_TITLE        — required
#   PR_URL          — required
#   MERGE_SHA       — required, full merge commit SHA
#   RUN_URL         — required, URL of the workflow run that produced this release
#   OUTPUT_FILE     — required, path to write the markdown body

: "${BROADCAST_FILE:?BROADCAST_FILE is required}"
: "${BLOCKSCOUT_URL:?BLOCKSCOUT_URL is required}"
: "${NETWORK_NAME:?NETWORK_NAME is required}"
: "${CHAIN_ID:?CHAIN_ID is required}"
: "${PR_NUMBER:?PR_NUMBER is required}"
: "${PR_TITLE:?PR_TITLE is required}"
: "${PR_URL:?PR_URL is required}"
: "${MERGE_SHA:?MERGE_SHA is required}"
: "${RUN_URL:?RUN_URL is required}"
: "${OUTPUT_FILE:?OUTPUT_FILE is required}"

if [[ ! -f "$BROADCAST_FILE" ]]; then
  echo "::error::Broadcast file not found: $BROADCAST_FILE"
  exit 1
fi

# Strip trailing slash from Blockscout URL so we can join with /address/...
BLOCKSCOUT_URL="${BLOCKSCOUT_URL%/}"

SHORT_SHA="${MERGE_SHA:0:7}"
DEPLOYER=$(jq -r '.transactions[0].from // empty' "$BROADCAST_FILE")
CREATE_COUNT=$(jq '[.transactions[] | select(.transactionType == "CREATE")] | length' "$BROADCAST_FILE")

{
  echo "> **Testnet deployment** — \`${NETWORK_NAME}\` (chain \`${CHAIN_ID}\`)"
  echo ""
  echo "Merged PR: [#${PR_NUMBER} ${PR_TITLE}](${PR_URL})"
  echo ""
  echo "Commit: \`${SHORT_SHA}\`"
  if [[ -n "$DEPLOYER" && "$DEPLOYER" != "null" ]]; then
    echo ""
    echo "Deployer: [\`${DEPLOYER}\`](${BLOCKSCOUT_URL}/address/${DEPLOYER})"
  fi
  echo ""

  if [[ "$CREATE_COUNT" -eq 0 ]]; then
    echo "_No contracts deployed in this run._"
  else
    echo "## Contracts"
    echo ""
    echo "| Contract | Address | Explorer |"
    echo "|----------|---------|----------|"
    # Escape pipes in contract names so they don't break the table.
    jq -r --arg blockscout "$BLOCKSCOUT_URL" '
      .transactions[]
      | select(.transactionType == "CREATE")
      | "| \(.contractName | gsub("\\|"; "\\|")) | `\(.contractAddress)` | [View](\($blockscout)/address/\(.contractAddress)) |"
    ' "$BROADCAST_FILE"
  fi

  echo ""
  echo "_Generated by [workflow run](${RUN_URL})._"
} > "$OUTPUT_FILE"

echo "Wrote release body to $OUTPUT_FILE (${CREATE_COUNT} contract(s))"
